### ISSUE TITLE
Docs pages not showing up inside Netlify CMS 

### ISSUE THREAD

**Issue by callhomesg** [stackbit-themes/libris-nextjs#14]
<img width="1006" alt="Screen Shot 2020-10-22 at 9 54 05 PM" src="https://user-images.githubusercontent.com/71583176/96881810-35d74780-14b1-11eb-93d6-3018f7ed1e46.png">

The individual documentation pages are not showing up inside NetlifyCMS unfortunately, as shown above. Not sure what is missing as I'm not all too familiar with Gatsby. I would ideally want non-technical folks to be able to edit the docs pages within the CMS, so that they don't have to use Github to write the docs or Stackbit's live editor.

This is my public repo - https://github.com/callhomesg/en-support-callhome
Used Gatsby with NetlifyCMS

**Comment by smnh** [comment]
Hi

Thanks for reporting!
I remember that NetlifyCMS had limited support with nested page
hierarchies. We will look into that and see what can be done to improve it.

Side question: did you try adding the page via stackbit studio? If you
created a site via Stackbit with Libris theme, Gatsby, and NetlifyCMS, then
you should be able to use Stackbit Studio to edit existing pages and add
new ones.

Best,

Simon Hanukaev
CTO, [image: Stackbit Logo] Stackbit <https://www.stackbit.com>

**Comment by callhomesg** [comment]
Thanks for the quick reply Simon! I see, so it's a NetlifyCMS issue. To think I spent hours trying to debug it! :( 

Yes I was able to edit it in Stackbit Studio, but my collaborator is more used to NetlifyCMS that's why i was thinking of keeping to it. I guess I'll just have to onboard him to Studio now...

Thanks again

**Comment by TomasBankauskas** [comment]
I will close this issue as no further activity occurs.
