### ISSUE TITLE
Docs page is not well supported

### ISSUE THREAD

**Issue by kennisdj05** [stackbit-themes/libris-nextjs#5]
This is an awesome theme and Stackbit looks awesome! However, I tried using this theme with Forestry, Netlify CMS, and Sanity. With all of them, trying to restructure the Docs page is not well supported and would likely have to be done outside the CMS itself, unless you wanted to keep the same structure that the theme ships with. In addition, with Sanity, the side menu is collapsed and doesn't show any text so you can't even tell that it's a menu when the page is first loaded unless you click on one of the closing brackets >. 

I could definitely just do the editing outside the CMS itself but I was looking for something where others could change the site from the CMS itself since they'd have no familiarity with GitHub or Markdown.

**Comment by TomasBankauskas** [comment]
I will close this issue as no further activity occurs.
